-- 1
(SELECT DISTINCT PNUMBER FROM EMPLOYEE,PROJECT,WORKS_ON WHERE SSN=ESSN AND PNO=PNUMBER AND LNAME='SMITH')
UNION 
(SELECT DISTINCT PNUMBER FROM EMPLOYEE,PROJECT,DEPARTMENT WHERE SSN=MGR_SSN AND DNUM=DNUMBER AND LNAME='SMITH');
-- 2
SELECT FNAME,MINIT,LNAME FROM EMPLOYEE WHERE NOT EXISTS (SELECT * FROM DEPENDENT WHERE SSN=ESSN);
-- 3
(SELECT SSN FROM EMPLOYEE WHERE DNO=5) UNION(SELECT S.SSN FROM EMPLOYEE AS E,EMPLOYEE AS S WHERE S.SSN=E.SUPER_SSN AND E.DNO=5);
-- 4
(SELECT PNAME,PNUMBER,PLOCATION FROM PROJECT WHERE DNUM=5)
INTERSECT
(SELECT PNAME,PNUMBER,PLOCATION FROM WORKS_ON,PROJECT WHERE ESSN='123456789' AND PNUMBER=PNO);
-- 5
(SELECT SSN FROM EMPLOYEE WHERE DNO=5) EXCEPT 
(SELECT W.ESSN FROM WORKS_ON AS W,PROJECT AS P,EMPLOYEE AS E WHERE E.SSN=W.ESSN AND W.PNO=P.PNUMBER AND P.PLOCATION='BELLAIRE');
-- 6
(SELECT FNAME AS NAME FROM EMPLOYEE) INTERSECT (SELECT DEPENDENT_NAME AS NAME FROM DEPENDENT);