CREATE TABLE EMPLOYEE(NAME VARCHAR(30),SSN VARCHAR(20) NOT NULL,GENDER CHAR,DNAME VARCHAR(20),PRIMARY KEY(SSN));
CREATE TABLE DEPARTMENT(DNAME VARCHAR(20),TIMES INT DEFAULT 0,PRIMARY KEY(DNAME));
ALTER TABLE EMPLOYEE ADD CONSTRAINT FKEY_DNAME FOREIGN KEY(DNAME) REFERENCES DEPARTMENT(DNAME);

CREATE FUNCTION F1()
RETURNS TRIGGER
LANGUAGE PLPGSQL AS 
$$
BEGIN
UPDATE DEPARTMENT SET TIMES=TIMES+1 WHERE NEW.DNAME=DEPARTMENT.DNAME;
RETURN NEW;
END;
$$;

CREATE TRIGGER F11
AFTER INSERT ON EMPLOYEE
FOR EACH ROW
EXECUTE PROCEDURE F1();

INSERT INTO DEPARTMENT VALUES('RESEARCH',0);
INSERT INTO DEPARTMENT VALUES('DATA SCIENCE',0);

SELECT * FROM DEPARTMENT;

INSERT INTO EMPLOYEE VALUES('RAM','123','M','RESEARCH');
INSERT INTO EMPLOYEE VALUES('SHYAM','124','M','RESEARCH');
INSERT INTO EMPLOYEE VALUES('SITA','125','F','RESEARCH');
INSERT INTO EMPLOYEE VALUES('SK','126','M','DATA SCIENCE');
INSERT INTO EMPLOYEE VALUES('PK','145','M','DATA SCIENCE');

SELECT * FROM EMPLOYEE;

CREATE FUNCTION F2()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
UPDATE DEPARTMENT SET TIMES=TIMES-1 WHERE OLD.DNAME=DEPARTMENT.DNAME;
RETURN OLD;
END;
$$;

CREATE TRIGGER F22 BEFORE DELETE
ON EMPLOYEE FOR EACH ROW
EXECUTE PROCEDURE F2();

DELETE FROM EMPLOYEE WHERE SSN='123';
DELETE FROM EMPLOYEE WHERE SSN='126';

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;


-- PROBLEM STATEMENT 2:

CREATE TABLE ORDER_ITEM(NAME VARCHAR(20) NOT NULL,QUANTITY INT,PRICE INT,ID VARCHAR(10) NOT NULL,PRIMARY KEY(ID));
CREATE TABLE SUMMARY_TABLE(ITEM_COUNT INT,PRICE INT);

CREATE FUNCTION F11()
RETURNS TRIGGER LANGUAGE PLPGSQL
AS $$
BEGIN 
UPDATE SUMMARY_TABLE SET ITEM_COUNT=ITEM_COUNT+1,PRICE=PRICE+NEW.QUANTITY*NEW.PRICE;
RETURN NEW;
END;
$$;

CREATE TRIGGER F111
AFTER INSERT 
ON ORDER_ITEM
FOR EACH ROW
EXECUTE PROCEDURE F11();

INSERT INTO SUMMARY_TABLE VALUES(0,0);
INSERT INTO ORDER_ITEM VALUES('MANGO',3,200,'FRUIT1');
INSERT INTO ORDER_ITEM VALUES('APPLE',5,1000,'FRUIT2');
SELECT * FROM ORDER_ITEM;
SELECT * FROM SUMMARY_TABLE;


